version: "3.9"
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - frontend
#      - api

    volumes:
      - /etc/letsencrypt/archive/pharmaref.online/:/etc/nginx/certs/

  frontend:
    build: ./frontend_service
