openapi: 3.0.3
info:
  title: Pharmacy Reference.
  version: 0.1.0
  description: Used to call Users related features, Drugs summaries and search and more.
  contact:
    name: Pharma Reference
    url: https://pharmaref.online
servers:
  - url: http://127.0.0.1:5000
    description: Local server.
  - url: https://pharmaref.online
    description: Demo server.
tags:
  - name: Info
    description: Heartbeat route
  - name: Users
    description: Information about the API users.
  - name: Summarizations
    description: Summarization info about generic drug.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-tokenInfoFunc: api_service.endpoints.auth.jwt

  schemas:
    HeartBeat:
      type: object
      properties:
        name:
          type: string
          description: Service name.

    ErrorResponse:
      description: Error response.
      type: object
      properties:
        message:
          type: string
          nullable: true
          description: Additional information about the error.

    User:
      type: object
      properties:
        id:
          type: integer
          description: ID of the user in DB.
        username:
          type: string
          description: User's name.
        password:
          type: string
          description: User's password.
        isDoctor:
          type: boolean
          description: Is User a doctor?

    Token:
      type: object
      properties:
        access_token:
          type: string
          description: Access JWT Token.

    Summarization:
      type: object
      properties:
        id:
          type: integer
          description: ID of Summarization.
        drugId:
          type: string
          description: ID of the drug
        text:
          type: string
          description: Summary text
        paperCount:
          type: integer
          description: Count of papers related to the drug_id search request

      example:
        id: 12
        drugId: 018DF2543374D301C22587500023AB7B
        text: Amoxicillin and beta-lactamase inhibitor is good.
        paperCount: 300

paths:
  /:
    get:
      tags:
        - Info
      description: Heartbeat endpoint for health checks.
      responses:
        "200":
          description: Return server information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeartBeat"
              example:
                name: api_server
  /users:
    post:
      tags:
        - Users
      summary: Create new User.
      description: Creates a new User
      requestBody:
        description: User's info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: |
            Returns created User.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: No authorization token provided
        "409":
          description: Item with already exist. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Conflict user with that name already exists.
        "415":
          description: Invalid content type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                detail: null
                status: 415
                title: Invalid Content-type (application/x-www-form-urlencoded),
                  expected JSON data
                type: about:blank
        "500":
          description: >
            Unhandled server error. Please provide information about this error
            to the support team.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: The server encountered an internal error and was unable to
                  complete your request. Either the server is overloaded or
                  there is an error in the application.

  "/tokens":
    get:
      tags:
        - Users
      responses:
        "200":
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
        "401":
          description: Unauthorized

    post:
      tags:
        - Users
      summary: Issue a new user JWT token.
      requestBody:
        description: User's name and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Returns Avatar object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              example:
                access_token: "xxxx.yyyyyy.zzzzzz"
        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials

  "/summarizations":
    get:
      tags:
        - Summarizations

      responses:
        "200":
          description: Summarization texts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Summarization"
        "401":
          description: Unauthorized

    post:
      tags:
        - Summarizations

      summary: Create a new Summarization.
      requestBody:
        description: Summarization's info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Summarization'

      responses:
        "200":
          description: Returns Summarization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summarization'

        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials

