openapi: 3.0.3
info:
  title: Pharmacy Reference.
  version: 0.1.0
  description: Used to call Users related features, Drugs summaries and search and more.
  contact:
    name: Pharma Reference
    url: https://pharmaref.online
servers:
  - url: http://127.0.0.1:5000
    description: Local server.
  - url: https://pharmaref.online
    description: Demo server.
tags:
  - name: Info
    description: Heartbeat route
  - name: Users
    description: Information about the API users.
  - name: Summarizations
    description: Summarization info about generic drug.
  - name: Drugs
    description: Summarization info about generic drug.
  - name: Shopping Lists
    description: Shopping List related endpoints

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HeartBeat:
      type: object
      properties:
        name:
          type: string
          description: Service name.

    ErrorResponse:
      description: Error response.
      type: object
      properties:
        message:
          type: string
          nullable: true
          description: Additional information about the error.

    User:
      type: object
      properties:
        id:
          type: integer
          description: ID of the user in DB.
        username:
          type: string
          description: User's name.
        password:
          type: string
          description: User's password.
        isDoctor:
          type: boolean
          description: Is User a doctor?

    Token:
      type: object
      properties:
        access_token:
          type: string
          description: Access JWT Token.

    Summarization:
      type: object
      properties:
        id:
          type: integer
          description: ID of Summarization.
        drugId:
          type: string
          description: ID of the drug
        text:
          type: string
          description: Summary text
        paperCount:
          type: integer
          description: Count of papers related to the drug_id search request

      example:
        id: 12
        drugId: 018DF2543374D301C22587500023AB7B
        text: Amoxicillin and beta-lactamase inhibitor is good.
        paperCount: 300

    Drug:
      type: object
      example: "{\n  \"components\": \"1 таблетка, вкрита оболонкою містить: 400 мг етамбутолу гідрохлориду, що відповідає вимогам Британської фармакопеї\",\n  \"country\": \"Нідерланди\",\n  \"drug_class\": \"Протитуберкульозні засоби.\",\n  \"form_factor\": \"таблетки, вкриті оболонкою, по 400 мг, по 1000 таблеток у банці пластиковій\",\n  \"generic_name\": \"Ethambutol\",\n  \"id\": \"F48D68E589D16390C2258869003A064D\",\n  \"instructuion_url\": \"http://www.drlz.com.ua/ibp/lz_www.nsf/id/D964E6C7F210426AC225886D00471901/$file/UA153730101_F48D.pdf\",\n  \"is_biologic\": false,\n  \"is_herbal\": false,\n  \"is_homeopaty\": false,\n  \"is_imunobiologic\": false,\n  \"is_recipe_needed\": \"за рецептом\",\n  \"name\": \"ЕТАМБУТОЛ\",\n  \"producer\": \"Свізера Юроп Б.В.\",\n  \"reg_id\": \"UA/15373/01/01\"\n}\n"

    ShoppingList:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        userId:
          type: integer
        drugs:
          type: array
          items:
            $ref: "#/components/schemas/Drug"
paths:
  /:
    get:
      tags:
        - Info
      description: Heartbeat endpoint for health checks.
      responses:
        "200":
          description: Return server information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HeartBeat"
              example:
                name: api_server
  /users:
    post:
      tags:
        - Users
      summary: Create new User.
      description: Creates a new User
      requestBody:
        description: User's info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: |
            Returns created User.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: No authorization token provided
        "409":
          description: Item with already exist. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Conflict user with that name already exists.
        "415":
          description: Invalid content type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                detail: null
                status: 415
                title: Invalid Content-type (application/x-www-form-urlencoded),
                  expected JSON data
                type: about:blank
        "500":
          description: >
            Unhandled server error. Please provide information about this error
            to the support team.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: The server encountered an internal error and was unable to
                  complete your request. Either the server is overloaded or
                  there is an error in the application.

  "/tokens":
    get:
      tags:
        - Users
      responses:
        "200":
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
        "401":
          description: Unauthorized

    post:
      tags:
        - Users
      summary: Issue a new user JWT token.
      requestBody:
        description: User's name and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Returns Avatar object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              example:
                access_token: "xxxx.yyyyyy.zzzzzz"
        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials

  "/summarizations":
    get:
      tags:
        - Summarizations

      responses:
        "200":
          description: Summarization texts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Summarization"
        "401":
          description: Unauthorized

    post:
      tags:
        - Summarizations

      summary: Create a new Summarization.
      requestBody:
        description: Summarization's info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Summarization'

      responses:
        "200":
          description: Returns Summarization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summarization'

        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials

  "/drugs":
    get:
      tags:
        - Drugs

      parameters:
        - in: query
          name: term
          schema:
            type: string
          required: false
        - in: query
          name: limit
          schema:
            type: integer
            default: 30
          required: false

      responses:
        "200":
          description: Registered in Ukraine Drugs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drug"
        "401":
          description: Unauthorized


  "/shopping_lists":
    get:
      tags:
        - Shopping Lists

      responses:
        "200":
          description: Set of users' lists got by JWT
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ShoppingList"
        "401":
          description: Unauthorized

    post:
      tags:
        - Shopping Lists

      summary: Create a new Shopping List.
      requestBody:
        description: Shopping list name
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "My List"

      responses:
        "200":
          description: Returns Shopping List.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingList'

        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials

  "/shopping_lists/{shoppingListId}/drugs":
    parameters:
     - in: path
       name: shoppingListId
       required: true
       description: Shopping List ID
       schema:
         type: integer

    get:
      tags:
        - Shopping Lists

      description: Used to retrieve User's (from JWT bearer) shopping list by ID

      responses:
        "200":
          description: Set of shopping list drugs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drug"
        "401":
          description: Unauthorized
        "404":
          description: Not Found

    post:
      tags:
        - Shopping Lists

      summary: Add Drug to Shopping List.
      requestBody:
        description: Drug ID to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drugId:
                  type: integer
              example:
                drugId: 6BEC590E29B0BDD1C22585FC00264396


      responses:
        "200":
          description: Returns Shopping List\s drugs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingList'

        "400":
          description: Wrong request. See response content for details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Detailed information about error.
        "401":
          description: Authentication information is missing or invalid.
          headers:
            WWW-Authenticate:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Wrong Auth credentials
