name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install poetry python-semantic-release==7.28.1
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"